import fs from 'fs';
import path from 'path';
import sqlite3 from 'sqlite3';
import { open } from 'sqlite';
import dotenv from 'dotenv';
import { createClient } from '@libsql/client';

dotenv.config();

const ALLOWED_EMAILS = [
  'sanojhardware@gmail.com',
  'krishleo439@gmail.com'
];

const PURGE_TABLES = [
  'products',
  'inventory',
  'stock_adjustments',
  'customers',
  'customer_transactions',
  'suppliers',
  'sales',
  'sales_items',
  'sales_returns',
  'sales_return_items',
  'purchase_orders',
  'purchase_order_items',
  'purchases',
  'purchase_returns',
  'purchase_return_items',
  'cheques',
  'cheque_registry',
  'credit_notes',
  'credit_note_usage',
  'credit_payments',
  'debit_notes',
  'expenses',
  'transactions',
  'shift_logs',
  'scanner_signals',
  'bill_holds',
  'delivery_notes',
  'quotations',
  'quotation_items',
  'sessions',
  'audit_logs',
  'sync_queue',
  'sync_pull_marker',
  'sync_conflicts',
  'deleted_records',
  'backup_logs'
];

async function purgeLocalSqlite() {
  console.log('\n========================================');
  console.log('--- PURGING LOCAL SQLITE (hardware.db) ---');
  console.log('========================================');

  const dbPath = path.resolve('hardware.db');
  if (!fs.existsSync(dbPath)) {
    throw new Error(`hardware.db not found at ${dbPath}`);
  }

  // Backup hardware.db before purge
  const backupPath = path.resolve(`hardware.db.pre_purge_${Date.now()}.bak`);
  fs.copyFileSync(dbPath, backupPath);
  console.log(`[Backup] Created safety snapshot: ${backupPath}`);

  const db = await open({
    filename: dbPath,
    driver: sqlite3.Database
  });

  // Get all existing tables in local DB
  const existingTablesResult = await db.all("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'");
  const existingTables = new Set(existingTablesResult.map(t => t.name));

  await db.run('PRAGMA foreign_keys = OFF');

  // 1. Purge operational tables
  for (const table of PURGE_TABLES) {
    if (existingTables.has(table)) {
      await db.run(`DELETE FROM "${table}"`);
      console.log(`[Local SQLite] Cleared table: ${table}`);
    }
  }

  // Also check for any other tables not in allowlist
  const preservedTables = new Set(['users', 'profiles', 'system_settings', 'app_settings', 'sqlite_sequence']);
  for (const table of existingTables) {
    if (!PURGE_TABLES.includes(table) && !preservedTables.has(table)) {
      try {
        await db.run(`DELETE FROM "${table}"`);
        console.log(`[Local SQLite] Cleared discovered non-preserved table: ${table}`);
      } catch (err) {
        console.warn(`[Local SQLite] Could not clear table ${table}:`, err.message);
      }
    }
  }

  // 2. Filter users and profiles strictly to the 2 allowed accounts
  const emailPlaceholders = ALLOWED_EMAILS.map(() => '?').join(', ');
  if (existingTables.has('users')) {
    await db.run(`DELETE FROM users WHERE LOWER(email) NOT IN (${emailPlaceholders})`, ...ALLOWED_EMAILS.map(e => e.toLowerCase()));
    console.log('[Local SQLite] Retained ONLY Super Admin & Krish Admin in users table.');
  }
  if (existingTables.has('profiles')) {
    await db.run(`DELETE FROM profiles WHERE LOWER(email) NOT IN (${emailPlaceholders})`, ...ALLOWED_EMAILS.map(e => e.toLowerCase()));
    console.log('[Local SQLite] Retained ONLY Super Admin & Krish Admin in profiles table.');
  }

  // 3. Reset sqlite_sequence
  try {
    await db.run('DELETE FROM sqlite_sequence');
    console.log('[Local SQLite] Reset sqlite_sequence autoincrement counters.');
  } catch (err) {
    console.warn('[Local SQLite] sqlite_sequence reset note:', err.message);
  }

  // 4. Reset system_settings invoice sequencing to 'INV001'
  if (existingTables.has('system_settings')) {
    try {
      await db.run("UPDATE system_settings SET next_invoice_number = 'INV001' WHERE id = 'global'");
      console.log("[Local SQLite] Set system_settings next_invoice_number = 'INV001'.");
    } catch (e) {
      try {
        await db.run("UPDATE system_settings SET next_invoice_number = 'INV001'");
        console.log("[Local SQLite] Set system_settings next_invoice_number = 'INV001'.");
      } catch (err) {
        console.warn('[Local SQLite] system_settings invoice sequence reset note:', err.message);
      }
    }
  }

  // Final sweep: ensure audit_logs generated by system_settings triggers are cleared
  if (existingTables.has('audit_logs')) {
    await db.run('DELETE FROM audit_logs');
    console.log('[Local SQLite] Cleared audit_logs.');
  }

  await db.run('PRAGMA foreign_keys = ON');
  await db.close();
  console.log('[Local SQLite] Purge completed successfully.');
}

async function purgeTursoCloud() {
  console.log('\n========================================');
  console.log('--- PURGING TURSO CLOUD DATABASE ---');
  console.log('========================================');

  const url = process.env.TURSO_DATABASE_URL;
  const authToken = process.env.TURSO_AUTH_TOKEN;

  if (!url || !authToken) {
    console.warn('[Turso Cloud] TURSO_DATABASE_URL or TURSO_AUTH_TOKEN not set in .env! Skipping Turso Cloud.');
    return;
  }

  const client = createClient({ url, authToken });

  // Get all existing tables in Turso DB
  const existingTablesResult = await client.execute("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'");
  const existingTables = new Set(existingTablesResult.rows.map(r => String(r.name)));

  // 1. Purge operational tables
  for (const table of PURGE_TABLES) {
    if (existingTables.has(table)) {
      try {
        await client.execute(`DELETE FROM "${table}"`);
        console.log(`[Turso Cloud] Cleared table: ${table}`);
      } catch (err) {
        console.warn(`[Turso Cloud] Error clearing table ${table}:`, err.message);
      }
    }
  }

  // Also check for any other tables not in allowlist
  const preservedTables = new Set(['users', 'profiles', 'system_settings', 'app_settings', 'sqlite_sequence']);
  for (const table of existingTables) {
    if (!PURGE_TABLES.includes(table) && !preservedTables.has(table)) {
      try {
        await client.execute(`DELETE FROM "${table}"`);
        console.log(`[Turso Cloud] Cleared discovered non-preserved table: ${table}`);
      } catch (err) {
        console.warn(`[Turso Cloud] Could not clear table ${table}:`, err.message);
      }
    }
  }

  // 2. Filter users and profiles strictly to the 2 allowed accounts
  const emailPlaceholders = ALLOWED_EMAILS.map(() => '?').join(', ');
  if (existingTables.has('users')) {
    await client.execute({
      sql: `DELETE FROM users WHERE LOWER(email) NOT IN (${emailPlaceholders})`,
      args: ALLOWED_EMAILS.map(e => e.toLowerCase())
    });
    console.log('[Turso Cloud] Retained ONLY Super Admin & Krish Admin in users table.');
  }
  if (existingTables.has('profiles')) {
    await client.execute({
      sql: `DELETE FROM profiles WHERE LOWER(email) NOT IN (${emailPlaceholders})`,
      args: ALLOWED_EMAILS.map(e => e.toLowerCase())
    });
    console.log('[Turso Cloud] Retained ONLY Super Admin & Krish Admin in profiles table.');
  }

  // 3. Reset sqlite_sequence
  try {
    await client.execute('DELETE FROM sqlite_sequence');
    console.log('[Turso Cloud] Reset sqlite_sequence autoincrement counters.');
  } catch (err) {
    console.warn('[Turso Cloud] sqlite_sequence reset note:', err.message);
  }

  // 4. Reset system_settings invoice sequencing to 'INV001'
  if (existingTables.has('system_settings')) {
    try {
      await client.execute("UPDATE system_settings SET next_invoice_number = 'INV001' WHERE id = 'global'");
      console.log("[Turso Cloud] Set system_settings next_invoice_number = 'INV001'.");
    } catch (e) {
      try {
        await client.execute("UPDATE system_settings SET next_invoice_number = 'INV001'");
        console.log("[Turso Cloud] Set system_settings next_invoice_number = 'INV001'.");
      } catch (err) {
        console.warn('[Turso Cloud] system_settings invoice sequence reset note:', err.message);
      }
    }
  }

  // Final sweep: ensure audit_logs generated by system_settings triggers are cleared
  if (existingTables.has('audit_logs')) {
    await client.execute('DELETE FROM audit_logs');
    console.log('[Turso Cloud] Cleared audit_logs.');
  }

  console.log('[Turso Cloud] Purge completed successfully.');
}

async function verifyAndPrintCounts() {
  console.log('\n========================================');
  console.log('--- VERIFICATION TABLE ---');
  console.log('========================================');

  const db = await open({
    filename: path.resolve('hardware.db'),
    driver: sqlite3.Database
  });

  const localTables = new Set((await db.all("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'")).map(t => t.name));

  let tursoClient = null;
  let tursoTables = new Set();
  if (process.env.TURSO_DATABASE_URL && process.env.TURSO_AUTH_TOKEN) {
    tursoClient = createClient({
      url: process.env.TURSO_DATABASE_URL,
      authToken: process.env.TURSO_AUTH_TOKEN
    });
    const tRes = await tursoClient.execute("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'");
    tursoTables = new Set(tRes.rows.map(r => String(r.name)));
  }

  const checkTables = [
    'users',
    'profiles',
    'system_settings',
    ...PURGE_TABLES
  ];

  const results = [];

  for (const tbl of checkTables) {
    let localCount = 'N/A';
    if (localTables.has(tbl)) {
      try {
        const row = await db.get(`SELECT COUNT(*) as c FROM "${tbl}"`);
        localCount = row.c;
      } catch (e) {
        localCount = 'ERR';
      }
    }

    let tursoCount = 'N/A';
    if (tursoClient && tursoTables.has(tbl)) {
      try {
        const res = await tursoClient.execute(`SELECT COUNT(*) as c FROM "${tbl}"`);
        tursoCount = res.rows[0].c;
      } catch (e) {
        tursoCount = 'ERR';
      }
    }

    results.push({
      Table: tbl,
      'Local SQLite': localCount,
      'Turso Cloud': tursoCount,
      Status: (tbl === 'users' || tbl === 'profiles')
        ? ((localCount === 2 && (tursoCount === 2 || tursoCount === 'N/A')) ? '✅ 2 USERS' : '❌ FAILED')
        : (tbl === 'system_settings')
        ? '✅ PRESERVED'
        : ((localCount === 0 || localCount === 'N/A') && (tursoCount === 0 || tursoCount === 'N/A') ? '✅ PURGED (0)' : '❌ NOT ZERO')
    });
  }

  console.table(results);

  // Print exact users in both
  const localUsers = await db.all('SELECT email, role FROM users');
  console.log('\n[Local SQLite] Remaining Users:', localUsers);

  if (tursoClient && tursoTables.has('users')) {
    const tUsers = await tursoClient.execute('SELECT email, role FROM users');
    console.log('[Turso Cloud] Remaining Users:', tUsers.rows);
  }

  // Print next invoice number
  if (localTables.has('system_settings')) {
    const s = await db.get('SELECT next_invoice_number FROM system_settings LIMIT 1');
    console.log('[Local SQLite] system_settings.next_invoice_number:', s?.next_invoice_number);
  }
  if (tursoClient && tursoTables.has('system_settings')) {
    const ts = await tursoClient.execute('SELECT next_invoice_number FROM system_settings LIMIT 1');
    console.log('[Turso Cloud] system_settings.next_invoice_number:', ts.rows[0]?.next_invoice_number);
  }

  await db.close();
}

async function main() {
  try {
    await purgeLocalSqlite();
    await purgeTursoCloud();
    await verifyAndPrintCounts();
    console.log('\n✅ Zero-Purge complete and verified.');
  } catch (err) {
    console.error('\n❌ Zero-Purge failed:', err);
    process.exit(1);
  }
}

main();
